import 'dart:io';
import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import 'package:biyahe_meter/core/models/trip_record.dart';

class ReceiptService {
  Future<Uint8List> buildPdfBytes(TripRecord trip) async {
    final doc = pw.Document();
    final dateFmt = DateFormat('MMM d, yyyy');
    final timeFmt = DateFormat('h:mm a');
    final money = NumberFormat.currency(locale: 'en_PH', symbol: 'PHP ');

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'BiyaheMeter PH',
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text('Digital Fare Receipt'),
              pw.Divider(),
              _row('Date', dateFmt.format(trip.startedAt)),
              _row('Start', timeFmt.format(trip.startedAt)),
              _row('End', timeFmt.format(trip.endedAt)),
              _row(
                'Duration',
                '${trip.duration.inMinutes} min ${trip.duration.inSeconds % 60}s',
              ),
              _row('Preset', trip.presetName),
              pw.SizedBox(height: 12),
              pw.Text(
                'Trip Metrics',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              _row('Distance', '${trip.distanceKm.toStringAsFixed(2)} km'),
              _row(
                'Avg Speed',
                '${trip.averageSpeedKmh.toStringAsFixed(1)} km/h',
              ),
              _row(
                'Waiting',
                '${trip.waitingMinutes.toStringAsFixed(1)} min',
              ),
              pw.SizedBox(height: 12),
              pw.Text(
                'Fare Breakdown',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              _row('Flagdown', money.format(trip.baseFare)),
              _row('Distance Fare', money.format(trip.distanceFare)),
              _row('Waiting Fare', money.format(trip.waitingFare)),
              if (trip.discountApplied)
                _row(
                  'Discount (${trip.discountPercent.toStringAsFixed(0)}%)',
                  '- ${money.format(trip.discountAmount)}',
                ),
              pw.Divider(),
              _row('TOTAL', money.format(trip.totalFare), bold: true),
              pw.SizedBox(height: 16),
              if (trip.startPoint != null)
                _row(
                  'Start GPS',
                  '${trip.startLat!.toStringAsFixed(5)}, ${trip.startLng!.toStringAsFixed(5)}',
                ),
              if (trip.endPoint != null)
                _row(
                  'End GPS',
                  '${trip.endLat!.toStringAsFixed(5)}, ${trip.endLng!.toStringAsFixed(5)}',
                ),
              pw.Spacer(),
              pw.Text(
                'Generated by BiyaheMeter PH · For passenger reference only',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
              ),
            ],
          );
        },
      ),
    );

    return doc.save();
  }

  pw.Widget _row(String label, String value, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label),
          pw.Text(
            value,
            style: bold
                ? pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14)
                : null,
          ),
        ],
      ),
    );
  }

  Future<void> sharePdf(TripRecord trip) async {
    final bytes = await buildPdfBytes(trip);
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/biyahemeter_receipt_${trip.id}.pdf');
    await file.writeAsBytes(bytes, flush: true);
    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path, mimeType: 'application/pdf')],
        subject: 'BiyaheMeter PH Trip Receipt',
        text: _summaryText(trip),
      ),
    );
  }

  Future<void> shareSummaryText(TripRecord trip) async {
    await SharePlus.instance.share(
      ShareParams(
        text: _summaryText(trip),
        subject: 'BiyaheMeter PH Trip Summary',
      ),
    );
  }

  Future<void> previewPdf(TripRecord trip) async {
    final bytes = await buildPdfBytes(trip);
    await Printing.layoutPdf(onLayout: (_) async => bytes);
  }

  String _summaryText(TripRecord trip) {
    final money = NumberFormat.currency(locale: 'en_PH', symbol: '₱');
    final buf = StringBuffer()
      ..writeln('BiyaheMeter PH — Trip Summary')
      ..writeln('Preset: ${trip.presetName}')
      ..writeln(
        'When: ${DateFormat('MMM d, yyyy h:mm a').format(trip.startedAt)}',
      )
      ..writeln('Distance: ${trip.distanceKm.toStringAsFixed(2)} km')
      ..writeln('Waiting: ${trip.waitingMinutes.toStringAsFixed(1)} min')
      ..writeln('Fare: ${money.format(trip.totalFare)}');
    if (trip.startPoint != null && trip.endPoint != null) {
      buf.writeln(
        'Route: https://www.google.com/maps/dir/?api=1'
        '&origin=${trip.startLat},${trip.startLng}'
        '&destination=${trip.endLat},${trip.endLng}',
      );
    }
    return buf.toString();
  }
}
